### ISSUE TITLE
Global disabledRules config option

### ISSUE THREAD

**Issue by eoinobrien** [chanzuckerberg/axe-storybook-testing#31]
Hi all,

An issue we experienced in work recently was the need to disable a specific low priority rule that affected a large number of stories while an upstream dependency worked to fix this issue.

To this we had to manually add the disabledRules parameter to all the stories affected.

I was wondering do you have any thoughts on making disabledRules a global config option. 

There are a number of reasons I could see for this.

1. In cases like the above where an issue affects a large number of stories
2. When one low priority issue cause the tests to fail, and the only option is to increase the severity (e.g. going from `minor` to `moderate` because [duplicate-id](https://dequeuniversity.com/rules/axe/4.2/duplicate-id?application=RuleDescription) fails a bunch)
3. Or to simply never run a check that you don't care about.

If this was something you think we should do, the obvious approach is to add a new cli config option.

Do you have any thoughts, I could possible take a shot at implementing this if you wished.

Cheers,
Eoin

**Comment by ahuth** [comment]
Hey @eoinobrien, thanks for raising this issue.

This is currently possible by adding setting `disabledRules` as a parameter in .storybook/preview.js. For example, something like

```js
export const parameters = {
  // ... any other parameters

  axe: {
    // Disable some rules for axe-storybook-testing. Note that this will **_not_** disable rules for
    // storybook's a11y addon.
    disabledRules: [
      "aria-dialog-name",
      "aria-progressbar-name",
    ],
  },
};
```

Having said that, it's not very discoverable. Adding a CLI option as you proposed would definitely be more discoverable. Or we could add some documentation specifically for globally disabling rules in this way.

Do you think this would meet your needs? Or we could add the CLI option to maximize discoverability.

**Comment by eoinobrien** [comment]
Hi Andrew,

Thanks I did not realize that at all. I will see if we can use that but it looks like it should meet our needs.

Could certainly be more discoverable though. Could we update the documentation?

**Comment by ahuth** [comment]
Added a note on how to globally disable rules in 6443ee82cff017cd59c0a73f7e4dae0df4653e1a.

I'm going to close this issue, but let me know if this ends up not meeting your needs.
