### ISSUE TITLE
Tests automatically fail when there are a lot of Stories to test

### ISSUE THREAD

**Issue by tstewart15** [chanzuckerberg/axe-storybook-testing#32]
I'm trying to onboard this package to my existing Storybook, and, out-of-the-box, I noticed that most of the tests were failing. After a certain number of tests, all subsequent tests fail w/ the error:
```
Error: page.evaluate: Evaluation failed: TypeError: Cannot read property 'add' of undefined
     at runAxe (eval at evaluate (:303:29), <anonymous>:4:26)
     at UtilityScript.evaluate (<anonymous>:305:22)
     at UtilityScript.<anonymous> (<anonymous>:1:44)
```

The errors start happening for every test after a certain number of Storybooks are tested:
![Screen Shot 2021-07-20 at 5 15 38 PM](https://user-images.githubusercontent.com/8942170/126411073-234069f7-c459-4034-b3ed-42ad457a7ea6.png)
(this goes on for about 500 failing tests in a row)

I wasn't sure why this was happening so I decided to re-run the tests, but only with one of the failing Stories present. The error went away:
![Screen Shot 2021-07-20 at 5 15 14 PM](https://user-images.githubusercontent.com/8942170/126411024-7529d0b4-a08b-4515-be86-e5e0db5302bc.png)
(notice that these were tests listed as failing in the previous screenshot)

Conclusion: It appears that axe-storybook-testing only works properly for 50-100 Stories, then starts failing all subsequent stories with the error above.

**Comment by ahuth** [comment]
Super weird, and thanks for the bug report, @tstewart15!

The error message makes it seem like `window.axeQueue` is getting clobbered: https://github.com/chanzuckerberg/axe-storybook-testing/blob/6443ee82cff017cd59c0a73f7e4dae0df4653e1a/src/browser/AxePage.ts#L23

Can you try running with [axe turned off ](https://github.com/chanzuckerberg/axe-storybook-testing#disabledrules)for the `BasePage` stories, please? Just want to rule out any pollution coming from other stories.

I'll work on making it less possible for that to happen, and will push up a beta version of the package to try out.

**Comment by tstewart15** [comment]
@ahuth Good call! Disabling the test for BasePage allowed the remaining tests to work as-expected. I suspect it has something to do with the `isFullPageStory` option, since this is the only test which includes this parameter.
![image](https://user-images.githubusercontent.com/8942170/126572987-bb100931-b0fa-48c6-be3f-2c3ac33bd300.png)

**Comment by ahuth** [comment]
Interesting. Do you know how `isFullPageStory` is being used in your project? I don't believe that's built-in to Storybook (or at least it's not an option I'm familiar with).

Is it being used by something that does anything with `window`? Or is it being used by a Storybook addon?

**Comment by tstewart15** [comment]
Ya, it's something being added in our project (sorry, I'm new to the project in addition to being new to Storybook in general, so I assumed it was coming from Storybook).

It appears when `isFullPageStory` is set, we clear the Preview DOM and replace it. I'm guessing we do this to test our components which represent the full document (ie. include `head` and `body`).

I suspect the resolution here is that axe-storybook-testing simply can't support this and we'll just need to skip this Story test (or attempt to fix this so that axe-storybook works on our side)?

**Comment by ahuth** [comment]
Thanks for looking into it!

I think both of these resolutions make sense:
- Like you said, skip running axe-storybook-testing on that story for now.
- On our end, I'll work on making axe-storybook-testing more resilient against things inadvertently modifying the globals it needs.

**Comment by ahuth** [comment]
Closing this as I think the short-term path forward is not running axe on the story in question.

Let me know if there's anything else I can do to help, or if you run into more issues.
