### ISSUE TITLE
Storybook 6.4 support

### ISSUE THREAD

**Issue by maddesigns** [chanzuckerberg/axe-storybook-testing#42]
I got a Storybook HTML 6.4.0-beta.13 error for each story: 
```bash
 Error: page.evaluate: Evaluation failed: TypeError: storybookClientApi.store is not a function
           at emitSetCurrentStory (eval at evaluate (:3:1339), <anonymous>:10:36)
           at t.default.evaluate (<anonymous>:3:1362)
           at t.default.<anonymous> (<anonymous>:1:44)
```
Anything I’m missing in my setup?

**Comment by maddesigns** [comment]
I stay on 6.3 for now.

**Comment by ahuth** [comment]
Once Storybook 6.4 is released (https://github.com/storybookjs/storybook/issues/15355), I'll merge #46 and publish a new major version of axe-storybook-testing that supports it.
