### ISSUE TITLE
Support selectors for disabledRule

### ISSUE THREAD

**Issue by Eric-B-Wu** [chanzuckerberg/axe-storybook-testing#53]
Currently, when disabling a rule, it can only be disabled for the specific story or globally. Supporting selectors would be a safer way of ignoring a violation across stories as Axe will then only ignore very specific elements and keep reporting violations on other elements of this rule.

**Comment by jeremiah-clothier** [comment]
>Not sure how to implement this, though. [axe-core's API](https://github.com/dequelabs/axe-core/blob/5a4babb815993dfe643f01a9921f105cab675de0/doc/API.md) lets us target specific selectors to check, but I'm not aware of any way to exclude selectors from rules.

I did some digging and may have found an API that would support this functionality using [an include-exclude object in axe-core's run method](https://github.com/dequelabs/axe-core/blob/5a4babb815993dfe643f01a9921f105cab675de0/doc/API.md#include-exclude-object)

I'm not sure what the integration would look like, but we may be able to update the code to accept this object and pass it along to where we call `axe.run(...)`?

**Comment by ahuth** [comment]
If I'm reading it right, that would let us exclude elements from being checked at all, but wouldn't let us exclude elements per rule.

Although maybe excluding elements from being checked at all is the best option we have.

**Comment by jeremiah-clothier** [comment]
>If I'm reading it right, that would let us exclude elements from being checked at all, but wouldn't let us exclude elements per rule.

🤦 Oh right, yeah I think you're right and this wouldn't allow that

**Comment by ahuth** [comment]
Could still be useful, though!

**Comment by leandroferreira** [comment]
@ahuth Is there still appetite for this feature? I'm looking into a way to send [Context](https://www.deque.com/axe/core-documentation/api-documentation/#context-parameter) to axe - similarly to sending options - where it can exclude certain elements from being tested.

**Comment by ahuth** [comment]
If there's a need for it, then definitely, @leandroferreira.

The only complication: I think the context will have to be json serializable, since it would have to be passed from Node to Playwright to the browser.

So I can imagine something like this totally working:

```
parameters: {
  axe: {
    context: {
      exclude: '.ad-banner'
      // or include: ...
      // or fromFrames: ...
      // etc.
    }
  }
}
```

but you wouldn't be able to use something like `document.querySelectorAll('whatever')` as the context.

**Comment by ahuth** [comment]
https://github.com/chanzuckerberg/axe-storybook-testing/pull/98

**Comment by leandroferreira** [comment]
Oh wow that was unbelievably quick, thank you so much! This will work perfectly for my use case :1st_place_medal:

**Comment by ahuth** [comment]
Released in https://github.com/chanzuckerberg/axe-storybook-testing/releases/tag/v8.2.0
