### ISSUE TITLE
reporter options markdown and doc fail to run tests

### ISSUE THREAD

**Issue by juruus** [chanzuckerberg/axe-storybook-testing#67]
Hi, 
my setup: 
- node v18.9.1
- axe-storybook-testing: 6.2.0
- storybook 6.5.12

if i run the tests with default config, everything works as it should **npx axe-storybook**
<img width="1207" alt="Screenshot 2022-10-29 at 12 45 09" src="https://user-images.githubusercontent.com/252967/198824841-5d734889-454c-4e6d-85c2-1582704f6b3e.png">

But with reporter options i get this: **npx axe-storybook --reporter markdown** 
<img width="916" alt="Screenshot 2022-10-29 at 12 44 45" src="https://user-images.githubusercontent.com/252967/198824845-29c9131a-5074-4657-93ec-70fdbac5613d.png">

**Comment by ahuth** [comment]
@juruus I've been looking into this, and unfortunately don't think there's anything we can do 😞 

Looks like [the markdown reporter renders the "test body"](https://github.com/mochajs/mocha/blob/8f3c37b6b77b6754cd9445204c536c1a0671450a/lib/reporters/markdown.js#L98), not the failure message.

In this case, the test body isn't super useful. I don't see a way to affect what the reporter prints, though.
