### ISSUE TITLE
Amend options for a rule

### ISSUE THREAD

**Issue by certainlyakey** [chanzuckerberg/axe-storybook-testing#87]
Thanks for the great tool! 

I have a trouble with a pseudoelement misfiring a `color-contrast` rule in a manner [described here](https://github.com/dequelabs/axe-core/issues/2781). Apparently, a way to ignore a pseudoelement when testing color contrast is to modify an option to include `ignorePseudo: true`, as in: 

```
axe.configure({
  rules: [{
    id: 'color-contrast-minor',
    matches: 'color-contrast-matches',
    any: ['color-contrast-minor']
  }],
  checks: [{
    id: 'color-contrast-minor',
    evaluate: 'color-contrast-evaluate',
    metadata: {
      impact: 'minor'
    },
    options: {
      contrastRatio: {
        normal: {
          expected: 4.5,
          minThreshold: 4.0
        },
        large: {
          expected: 3,
          minThreshold: 2.5
        }
      },
      ignoreUnicode: true,
      ignoreLength: false,
      ignorePseudo: false,
      boldValue: 700,
      boldTextPt: 14,
      largeTextPt: 18,
      shadowOutlineEmMax: 0.1
    }
  }]
});
```

I however have no idea how to add this option – `runOptions` of axe-storybook-testing seems to correspond to `axe.run()` rather than `axe.configure()`. Is there any way to set this `ignorePseudo` option before running it?

**Comment by ahuth** [comment]
Hi, thanks for raising this issue. You're right - there's no way right now to pass anything to `axe.configure`, unfortunately 😞.

I'll work on adding the ability to pass config to `axe.configure` today.

**Comment by ahuth** [comment]
@certainlyakey can you give me more specifics about the color contrast issue you're running into, and which version of axe-core you're using?

I'm trying to come up with a way to test out a solution, but can't reproduce the issues from https://github.com/dequelabs/axe-core/issues/2781 (which seem to be mostly `::after` content that doesn't overlap any text).

**Comment by ahuth** [comment]
This should be fixed in v7.2.0.

@certainlyakey can you try it out, please, and let me know if there's still an issue?

You can now pass a `config` parameter (to either the story, component, or globally) with anything you want to pass to `axe.configure`:

```js
parameters: {
  axe: {
    config: {
      checks: [ ... ]
    }
  }
}
```

**Comment by roypearce** [comment]
This is a great feature, can you expose this in the documentation? Maybe also include a better callout that this can be done in `preview.js` as well?

**Comment by ahuth** [comment]
Thanks @roypearce!

This feature is in the readme at https://github.com/chanzuckerberg/axe-storybook-testing?tab=readme-ov-file#config. Although it's pretty generic, and maybe it should have a more specific example?
